sudo: required

language: generic

sevices:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t onlyrice/docker-react-app -f dockerfile.dev .

script:
 - docker run -e CI=true onlyrice/docker-react-app npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react-app"
 env: "Dockerreactapp-env"
 bucket_name: "elasticbeanstalk-us-east-1-986104995910"
 bucket_path: "docker-react-app"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_ACCESS_KEY


