sudo: required

language: generic

sevices:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t onlyrice/docker-react-app -f dockerfile.dev .

script:
 - docker run -e CI=true onlyrice/docker-react-app npm run test -- --coverage

after_success:
 - echo "Test success"